# Test configuration for quick local testing
research_areas:
  - machine learning
  - AI

categories:
  - cs.AI
  - cs.LG

keywords:
  - neural networks
  - deep learning

sources:
  arxiv_api: true
  semantic_scholar: false  # Disable to avoid rate limiting
  enrich_with_papers_with_code: false  # Disable slow enrichment
  papers_with_code: false
  github_trending: false  # Disable to avoid timezone issues in test

filters:
  min_engagement_score: 1.0
  max_days_old: 1  # Very short for testing

email:
  max_papers_per_email: 2
  include_abstracts: true
  include_code_links: true
  include_pdf_links: true
  language: "English"
