name: Test workflow
on:
  workflow_dispatch:
    inputs:
      research_areas:
        description: 'Research areas (comma-separated, e.g., "machine learning,computer vision")'
        required: false
        type: string
      categories:
        description: 'ArXiv categories (comma-separated, e.g., "cs.LG,cs.CV,cs.AI")'
        required: false
        type: string
      keywords:
        description: 'Keywords (comma-separated, e.g., "neural networks,transformers,deep learning")'
        required: false
        type: string
      max_papers:
        description: 'Maximum number of papers to include (test limit: 3)'
        required: false
        type: number
        default: 3

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Shorter timeout for faster testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Create test user interests config
        run: |
          mkdir -p config
          cat > config/user_interests_dynamic.yml << EOF
          # Test configuration for ArXiv Weekly Popular
          # This file is created from GitHub Actions test inputs
          
          research_areas:
          EOF
          
          # Add research areas from input or use test defaults
          AREAS="${{ github.event.inputs.research_areas || 'LLM,AI,Prompt' }}"
          echo "$AREAS" | tr ',' '\n' | sed 's/^/  - /' | sed 's/^  - *$//' | grep -v '^  - $' >> config/user_interests_dynamic.yml
          
          # Add categories section
          cat >> config/user_interests_dynamic.yml << EOF
          
          categories:
          EOF
          
          CATEGORIES="${{ github.event.inputs.categories || 'cs.AI,cs.CV,cs.LG,cs.CL' }}"
          echo "$CATEGORIES" | tr ',' '\n' | sed 's/^/  - /' | sed 's/^  - *$//' | grep -v '^  - $' >> config/user_interests_dynamic.yml
          
          # Add keywords section
          cat >> config/user_interests_dynamic.yml << EOF
          
          keywords:
          EOF
          
          KEYWORDS="${{ github.event.inputs.keywords || 'transformers,large language model,prompt,evaluation' }}"
          echo "$KEYWORDS" | tr ',' '\n' | sed 's/^/  - /' | sed 's/^  - *$//' | grep -v '^  - $' >> config/user_interests_dynamic.yml
          
          # Add source configuration optimized for speed testing
          cat >> config/user_interests_dynamic.yml << EOF
          
          sources:
            arxiv_api: true
            semantic_scholar: false  # Disable to avoid rate limiting for testing
            enrich_with_papers_with_code: true  # Enable to show code buttons in test emails
            papers_with_code: false
            github_trending: false  # Disable to speed up testing
          
          filters:
            min_engagement_score: 1.0  # Lower threshold for testing
            max_days_old: 2  # Very short period for testing
          
          email:
            max_papers_per_email: ${{ github.event.inputs.max_papers || 3 }}
            include_abstracts: true
            include_code_links: true
            include_pdf_links: true
            language: "English"
          EOF
          
          echo "Generated test configuration:"
          cat config/user_interests_dynamic.yml

      - name: Run ArXiv Weekly Popular Test
        env:
          # Email configuration (required)
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER: ${{ secrets.RECEIVER }}
          
          # API tokens (optional but recommended)
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # LLM configuration (use cloud API for faster testing)
          USE_LLM_API: 'true'  # Use cloud API instead of local model for speed
          USE_LOCAL_MODEL: 'false'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE || 'English' }}
          
          # Fast testing configuration
          MAX_PAPER_NUM: ${{ github.event.inputs.max_papers || 3 }}
          DAYS_BACK: '2'  # Very short period for testing
          
          # Configuration file override
          USER_INTERESTS_CONFIG: config/user_interests_dynamic.yml
          
        run: |
          echo "Starting ArXiv Weekly Popular TEST with engagement-based discovery..."
          echo "Research Areas: ${{ github.event.inputs.research_areas || 'LLM,AI,Prompt' }}"
          echo "Categories: ${{ github.event.inputs.categories || 'cs.AI,cs.CV,cs.LG,cs.CL' }}"
          echo "Keywords: ${{ github.event.inputs.keywords || 'transformers,large language model,prompt,evaluation' }}"
          echo "Max Papers (Test): ${{ github.event.inputs.max_papers || 3 }}"
          echo "Days Back (Test): 2"
          echo "LLM: Cloud API (faster for testing)"
          echo "Sources: arXiv only (fast mode)"
          echo ""
          echo "Running in DEBUG mode for testing..."
          
          uv run main.py --debug
